### ISSUE TITLE
Confusing UI

### ISSUE THREAD

**Issue by awrog** [david-szabo97/grav-plugin-admin-addon-user-manager#22]
Fields and values are not very well located on screen.

![screenshot - 9_19_2017 3_29_58 pm](https://user-images.githubusercontent.com/12153667/30594914-ebe8a8f2-9d4f-11e7-9d15-e8558658b5c8.png)

**Comment by david-szabo97** [comment]
Hi there!

Is this the group form? I can't seem to reproduce this.

![image](https://user-images.githubusercontent.com/2256104/30603844-26d889dc-9d69-11e7-9268-8f35b3fab802.png)

**Comment by awrog** [comment]
David,

Thanks for your reply.
Oddly, all is fine now.... Changing the zoomfactor also has no impact.
I'll close the ticket.

**Comment by awrog** [comment]
Hi David, I have found the offending screen: it occurs in the user manager
![screenshot - 9_22_2017 10_19_50 am](https://user-images.githubusercontent.com/12153667/30735557-c0db80b2-9f7f-11e7-801c-60f397d06ce6.png)

**Comment by david-szabo97** [comment]
The user form is built into the Grav Admin Plugin, so it is unrelated to
this plugin.

**Comment by adrianw** [comment]
I've found that this issue happens when on screen of certain widths, for example if in chrome you set to a profile of dimensions 1280x800 the options get staggered, as you mentioned I think it could be an issue with the underlying admin plugin though as I noticed in field.html.twig (around line 55) it's using a class size-2-3 which isn't defined anywhere, did you report this?

**Comment by david-szabo97** [comment]
@adrianw I just opened a PR to fix it.

https://github.com/getgrav/grav-plugin-admin/pull/1379

**Comment by david-szabo97** [comment]
Added temporary fix in v2.1.0
