### ISSUE TITLE
Ideas: Tabs? Segments for filters?

### ISSUE THREAD

**Issue by filisko** [david-szabo97/grav-plugin-admin-addon-user-manager#32]
Hi,
Would it be better if we create only one page in the admin panel which could be called something like.. Security, Access Control, simply 'Users', or whatever, and place the current pages into tabs?
This way I think that the admin panel will look cleaner?

I think that another interesting thing could be to create something like "segments"  for the filters, which is basically a way to save your filters and reuse them just with a click and don't have to write them again and again, or another alternative I think is to create a better GUI for the filters.

Thanks for all!

**Comment by david-szabo97** [comment]
Hi! I agree with both of your recommendations. I wanted to implement saved
filters but I always skipped it.

I want the filter to be fully customizable, that's why it is not a gui.
Later we might add a gui and make the current filter to be the expert mode.

I will look into these next week and setup them as a separate issue so we
can track them better.

Thank you, have a nice weekend!

**Comment by david-szabo97** [comment]
Grav v1.7.0 has a built-in interface for managing users and groups. 🎉 I'm discontinuing the plugin. Thanks for using my plugin for the time being! 🙇
