### ISSUE TITLE
Group access not working properly

### ISSUE THREAD

**Issue by tlflow** [david-szabo97/grav-plugin-admin-addon-user-manager#39]
"Force Visible to Groups" and "Force Editable to Groups" works only when "admin.pages" is selected for each individual in the group. Setting admin.pages for the group doesn't seem to be enough. 

Also, when setting admin.pages the group now have access to change pages they shouldn't even see. Am I missing something?

**Comment by david-szabo97** [comment]
Hi @tlflow  !

Sorry, I never heard about "Force Visible to Groups" and "Force Editable to Groups".

Can you give me the steps to reproduce your issue?

**Comment by tlflow** [comment]
My apologies. Issue is actually with “Users Page Ownership” which is suppossed to play nice with this one. If I’m not mistaken it’s supposed to add these fields to all pages and then you can manually add the custom group to individual pages and it’s children. I think.

-

Terence

**Comment by david-szabo97** [comment]
Seems like that plugin had a similar 'Users' feature. A page to list out all users and allow them to be edited.
I don't know how that plugin works, but my plugin doesn't change anything in the permission system. So that issue may be related to that plugin.

Do you have the same issue without my plugin?

**Comment by tlflow** [comment]
I think you're right. Your plugin works just fine. It's the other one that's a little off. Thanks for looking into this though.
