### ISSUE TITLE
Error: Template "default.html.twig" is not defined

### ISSUE THREAD

**Issue by fl02** [david-szabo97/grav-plugin-admin-addon-user-manager#43]
This is an issue I first reported in the Grav admin plugin tracker: https://github.com/getgrav/grav-plugin-admin/issues/1450

Issue arises when clicking the »Login as«-button on a user page of the »admin-addon-user-manager«-plugin [v2.1.5]. A message pops up asking me whether I really want to leave the page as there are unsaved changes. I click »continue« and am presented with this error message:

    RuntimeException (400)
    Template "default.html.twig" is not defined.

Uninstallation of that plugin does resolve the issue.

**Comment by david-szabo97** [comment]
@crumblingwalls 
I can't reproduce this in latest version. Login As button works as expected. No errors.

Grav v1.4.5
Admin Panel  v1.8.2
Admin Addon User Manager  v2.1.5

**Comment by hleen** [comment]
Had same problem, restore of website was required...
It might have something to do with user groups.

**Comment by david-szabo97** [comment]
Are you trying to login as a non-admin user? That might cause problem.

**Comment by hleen** [comment]
Yes, that is what I tried. Login in the backend. The user was member of a usergroup that did not have all rights in the backend.

**Comment by fl02** [comment]
Same for me, sorry for not mentioning it earlier: the user I am trying to login in with is a non-admin user.

**Comment by david-szabo97** [comment]
That makes sense. "Login As" is meant only for admins. It tries to redirect you to the admin page so I guess that causes the issue. I may look into this and disable the button when the user is not an admin or site user.

**Comment by david-szabo97** [comment]
Also I will redirect non-admins to the home page.

**Comment by zyrx** [comment]
This is actually an issue due to when you perform the action `Login As` with a given user without access to admin panel, `Grav`'s template engine is looking for the file `default.html.twig` in order to display the default plugin page, however there is no `default.html.twig` file in `grav-plugin-admin`'s default template, `grav`.

Not sure if there is a reason for `grav-plugin-admin`'s developers to omiting that file, or maybe is just that nobody notice this issue before, but I think the easiest way to fix this is creating the `default.html.twig` file in `grav-plugin-admin`'s templates directory adding the following code:

```twig
# user/plugins/admin/themes/grav/templates/default.html.twig
{% include 'login.html.twig' %}
```

That way, when you do `Login As` without having enough permissions for that user, you'll get the login page with the message `Access Denied` and the buttons `Back` and `Logout` instead of the Error page.
